.PHONY: build
build:
		go build -v ./cmd/apiserver


.PHONY: test
test:
	go mod tidy
	go test -v -timeout 30s ./ ...

.DEFAULT_GOAL := build


.PHONY: tidy
tidy:
	go mod tidy

.DEFAULT_GOAL := build


.PHONY: pprof
pprof:
	pprof

